### ISSUE TITLE
Mac build does not show correct version

### ISSUE THREAD

**Issue by gcoco** [libusb/libusb-compat-0.1#11]
When building on Mac (10.11 using omebrew) the version of the dylib does not match the AC_INIT value. This is for the 0.1.15 and 0.1.16-rc2 release.

`./autogen.sh && make`
`libtool: link: gcc -dynamiclib  -o .libs/libusb-0.1.4.dylib  .libs/libusb_la-core.o   -L/usr/local/Cellar/libusb/1.0.21/lib -lusb-1.0  -g -O2   -install_name  /usr/local/lib/libusb-0.1.4.dylib -compatibility_version 9 -current_version 9.4 -Wl,-single_module`
`libtool: link: (cd ".libs" && rm -f "libusb.dylib" && ln -s "libusb-0.1.4.dylib" "libusb.dylib")`

I cannot figure out where the 0.1.4 is coming from.
Any chance this can be fixed to reflect the build (eg. 0.1.15 => libusb-0.1.5.dylib)

**Comment by hjelmn** [comment]
You are confusing library compatibility versioning with official versioning.

See:

https://unix.stackexchange.com/questions/475/how-do-so-shared-object-numbers-work
