### ISSUE TITLE
move libusb/libusb-compat-0.1 to libusb/libusb-compat-0.1-old (or not) and move hjelmn/libusb-compat-0.1 to libusb/libusb-compat and import all commits

### ISSUE THREAD

**Issue by Neustradamus** [libusb/libusb-compat-0.1#14]
For be more profesional etc...

First, it is possible to :
- move libusb/libusb-compat-0.1 to libusb/libusb-compat-0.1-old
- or keep like this

And after :
- move hjelmn/libusb-compat-0.1 to libusb/libusb-compat
- import all commits from "libusb/libusb-compat-0.1" to new libusb/libusb-compat

It will be better, I do not understand the fork ;)

And work now only on libusb-compat.

Fork will be note lost...
Redirections will be here.

https://help.github.com/articles/about-repository-transfers/

**Comment by mcuee** [comment]
The package name is libusb-compat-0.1 and please do not change the name.

**Comment by mcuee** [comment]
Personally I think the move is not necessary.

**Comment by mcuee** [comment]
Close this for now. Feel free to reopen if someone feels strong about this.

**Comment by Neustradamus** [comment]
@mcuee: It is not solved!

Please reopen this ticket!

**Comment by mcuee** [comment]
I do not think this is requied.

**Comment by mcuee** [comment]
Close this one.

**Comment by Neustradamus** [comment]
Code search is based on upstream, the solution if not a transfer, it is possible to detach:
- https://github.com/libusb/libusb-compat-0.1/issues/17

**Comment by mcuee** [comment]
Sorry but no, we will not deal with this.
