### ISSUE TITLE
Detach this fork from upstream

### ISSUE THREAD

**Issue by Neustradamus** [libusb/libusb-compat-0.1#17]
Can you detach this fork from upstream?

Contact GitHub: "Attach, detach, or reroute forks"
- https://github.com/contact
- https://support.github.com/contact?tags=rr-forks

Thanks in advance.

**Comment by mcuee** [comment]
I do not think this is required.

**Comment by Neustradamus** [comment]
It is better to have directly the best place and for search code in this repository instead of upstream.

**Comment by Neustradamus** [comment]
@libusb team, @hjelmn, @mcuee: My request always exists, can you look it?

Thanks in advance.

**Comment by mcuee** [comment]
No, we will not deal with this.
