### ISSUE TITLE
Rename libusb-compat-0.1 to libusb-compat

### ISSUE THREAD

**Issue by Neustradamus** [libusb/libusb-compat-0.1#18]
Can you rename libusb-compat-0.1 to libusb-compat?

Thanks in advance.

**Comment by mcuee** [comment]
I do not think this is required and it will cause unnecessary job for the distro maintainers.

**Comment by Neustradamus** [comment]
@mcuee: How it will be possible to have a 0.2 or 1.0 version ?

**Comment by Neustradamus** [comment]
No problem in distro:
- https://repology.org/project/libusb/versions
- https://repology.org/project/libusb0/versions

**Comment by Neustradamus** [comment]
Note: When you rename the repository, the old link is redirected to new without any problems.

**Comment by hjelmn** [comment]
This library providescompatibility with libusb 0.1 hence the name. We have no intention of changing it at this point.
