### ISSUE TITLE
Not able to run autogen successfully on centos 7 , When all required tools like autoconf, pkconfig, archive and libtool are already installed.

### ISSUE THREAD

**Issue by gandharav** [libusb/libusb-compat-0.1#21]
sh autogen.sh
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
configure.ac:34: error: possibly undefined macro: AU_CHECK_LIB_SONAME
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:41: error: possibly undefined macro: AU_HAVE_GNU_ERRNO_H

**Comment by mcuee** [comment]
You need automake, autoconf and libtool. Have you installed automake?
