### ISSUE TITLE
Windows mingw64 github action 

### ISSUE THREAD

**Issue by mcuee** [libusb/libusb-compat-0.1#22]
I have created the following github action for mingw64 based on the corresponding file (https://github.com/libusb/libusb/blob/master/.github/workflows/msys2.yml) but it oes not work, very strange.

My file is like this.
https://github.com/mcuee/libusb-compat-0.1/blob/mingw_test/.github/workflows/msys2.yml

It keeps complaining that libtool is not present, but there is no issue on my local MSYS2 installation (up-to-date).

**Comment by mcuee** [comment]
@Youw and @tormodvolden 
Just wondering if you can help here. I have no ideas why it failed.

**Comment by mcuee** [comment]
I have created PR #24 to address this issue.
* https://github.com/libusb/libusb-compat-0.1/pull/24

**Comment by Youw** [comment]
My experience with Github actions *mostly* tight with what is used by [hidapi build system](https://github.com/libusb/hidapi/blob/master/.github/workflows/builds.yml).
It has a MinGW build as well, but it is a bit different from #24 as it uses CMake version of the build and doesn't have any external dependencies.

**Comment by mcuee** [comment]
Thanks. I have sorted out the issue.
